---
exclude_paths:
  - tmp
  - vendor

detectors:
  DataClump:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  FeatureEnvy:
    enabled: false
  UtilityFunction:
    enabled: false


  #
  # Project rules
  #
  UncommunicativeModuleName:
    accept:
      - Active911
  #
  # Global Rules
  #
  LongParameterList:
    max_params: 4
  NestedIterators:
    enabled: true
    exclude: [ ]
    max_allowed_nesting: 2
    ignore_iterators:
      - tap
  TooManyInstanceVariables:
    max_instance_variables: 5
  TooManyStatements:
    max_statements: 15
