---
exclude_paths:
  - tmp
  - vendor

detectors:
  DataClump:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  FeatureEnvy:
    enabled: false
  IrresponsibleModule:
    enabled: false
  LongParameterList:
    max_params: 4

  TooManyInstanceVariables:
    max_instance_variables: 5

  #
  # Project rules
  #
  UncommunicativeModuleName:
    accept:
      - Active911

  UtilityFunction:
    enabled: false

  #
  # Global Rules
  #
  NestedIterators:
    enabled: true
    exclude: [ ]
    max_allowed_nesting: 2
    ignore_iterators:
      - tap
  TooManyStatements:
    max_statements: 15
